### ISSUE TITLE
[CS:S] Disconnect: Couldn't verify your, or the server's connection to Steam..

### ISSUE THREAD

**Issue by Lightningblade** [shavitush/bhoptimer#1047]
![image](https://user-images.githubusercontent.com/30607152/116463590-27585700-a86b-11eb-8833-15c882dcf335.png)

When the plugin loads I am not able to connect to the server due to the screenshot above.

This only happens when the shavit plugin is loaded. If it errors due to a lack or misconfiguration of the database file I am able to connect fine.

The only things installed on the server are MM, SM, Tickrate enabler and the bhoptimer.

**Comment by hermansimensen** [comment]
It's because of this. https://github.com/shavitush/bhoptimer/blob/very_good_yes/addons/sourcemod/scripting/shavit-core.sp#L2469

It doesn't really support late verification

**Comment by Lightningblade** [comment]
Is there a workaround?

**Comment by hermansimensen** [comment]
If you're just planning to use it for LAN single player you could just delete that line

**Comment by rtldg** [comment]
> Is there a workaround?

make sure your server and your game are connected to steam

that can sometimes happen right after starting a server and before the server was able to connect to steam

**Comment by Lightningblade** [comment]
> 
> 
> > Is there a workaround?
> 
> make sure your server and your game are connected to steam
> 
> that can sometimes happen right after starting a server and before the server was able to connect to steam

I reproduced this multiple times. It works without the plugins. It doesn't with. Across multiple days.

> 
> 
> If you're just planning to use it for LAN single player you could just delete that line

No, it is supposed to be an online server.

**Comment by rtldg** [comment]
This has been in the timer for 5 years and I can't find any issues about it. It seems reasonable to say that it's a problem on your end with the server or game client connecting to steam.

The timer is the reason for kicking yes, but that's because it can't get the player's steam id which isn't the timer's fault.

Make sure your game has a steam connection or whatever is needed.

If you're hosting it on a VPS or something, then you should make sure whatever connections and ports it uses for steam aren't blocked.
You should see something like in the server console
```
Connection to Steam servers successful.
   Public IP is 1.1.1.1.
Assigned anonymous gameserver Steam ID [A:1:123123123:12312].
```

**Comment by BoomShotKapow** [comment]
I know this is a bit old, but I just wanted to include the fix I had to implement when I had this same issue. In my case, when I installed the [connect](https://forums.alliedmods.net/showthread.php?t=162489) extension, this started to happen.

34fb7b2af3acbe85c0fa39e7076fb82c97f8f0f3
