### ISSUE TITLE
Zones drop down after being placed.

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#111]
This happened after grid snapping was added, imo grid snapping should not work vertically just horizontally.

This video show's what I mean: https://www.youtube.com/watch?v=Vd3pYLnjR5Y

If you adjust it using the controls to touch the ground then confirm the zone the bottom will be clipped into the ground.

**Comment by shavitush** [comment]
i'm really sorry but i think i don't understand

**Comment by Technoblazed** [comment]
^

**Comment by StrafeHack** [comment]
@shavitush 
I knew this would be a problem to explain it.

Ok so, basically look at the bottom of the zone, ignore the 3D part when placing, after I press (1. Yes) the zones is placed but the zone is lower, idk by how many units.

I chose a bad map to show it on but if it was a different one you would see the zone hovering in the first part.

**Comment by shavitush** [comment]
oh.. that's part of what i've been doing for cs:s because the ground would makes the bottom part of the visualization invisible, so i made it go up vertically by 2 units.
it's only visual but yeah i understand now. should it be always 'clipped to the ground' or be a bit higher, like it is when you setup zones?

**Comment by shavitush** [comment]
alright
