### ISSUE TITLE
native to set players time (and preferably other timer variables)

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#115]
Basically Shavit_GetTimer but the opposite, Shavit_SetTimer?

Basically I want to hopefully do some TAS runs using host_timescale and a CP plugin. I can save all the location, angles and speed obviously and even save the players timer details, but I need to be able to set them again when I use a CP.

I'd definately prefer this over a "Shavit_SetClientTime" as the other statistics will get quite messed up over time.

**Comment by StrafeHack** [comment]
Hmm, to be honest setting the style is kind of useless although that could be useful for someone, who knows.
The timer can already be stopped and started from existing natives.

So if you are willing to add this I would suggest, updating Shavit_GetTimer to include strafe count and sync and then make the new native able to set time, jumps, strafes and sync.

**Comment by shavitush** [comment]
> I would suggest, updating Shavit_GetTimer to include strafe count and sync 

I have only made `Shavit_GetTimer` because I didn't realize converting between other data types (considering SourceMod only allows me to use `int` for natives) will not result in data loss at all; after I've realized it, I made different Get\* natives, such as `Shavit_GetClientTime` and `Shavit_GetClientJump`.
That's because SourceMod wouldn't allow me to use a null reference just to grab less variables than what the lets me. For example:
```
Shavit_GetTimer(client, time, null, style, null);
```

That's why I see `Shavit_GetTimer` as deprecated and only keep it there to work with older plugins like the HUD, which will eventually be updated to not use `Shavit_GetTimer` at all!

**Comment by StrafeHack** [comment]
Uhm @shavitush I just thought of something that might be a problem for me maybe you can confirm it.

If you add these stocks and it's built into a cp plugin, that will be fine for doing tas times but will the bot record all the movement or just the time running?

**Comment by shavitush** [comment]
I could add a native that sets the replay tick for a player to.. something you set within the native, and then get rid of the 'future frames'.

**Comment by StrafeHack** [comment]
That sounds perfect and easy to use yep

**Comment by shavitush** [comment]
see #158
