### ISSUE TITLE
time/velocity difference does not appear

### ISSUE THREAD

**Issue by titanrawr** [shavitush/bhoptimer#1210]
On both my windows and linux CS:S server, time difference and velocity difference do not appear on the HUD in bhop timer 3.4.2. I have a LAN running bhop timer 3.3.0 where time diff is working just fine. Not sure if I'm missing something here. This is on meta mod 1.11.0 build 1155, and sourcemod 1.11.0 build 6952.

**Comment by rtldg** [comment]
I was busy getting food so that's good you were able to resolve it but I'll leave my message here anyway:

A couple things to do for it:
- Grab the [closestpos extension](https://github.com/rtldg/sm_closestpos/releases/tag/v1.1.1) and install it so the time-difference calculation doesn't slow the server down.
- You might have to enable the cvar (`shavit_replay_timedifference`) in `cstrike/cfg/sourcemod/plugin.shavit-replay-playback.cfg`, but you can ignore most of the rest of the cvars as they aren't used when closestpos is used.
- Check if it's enable in `!hud`. If it's not on by default then you can change the defaults for new users with the cvars `shavit_hud_default` and `shavit_hud2_default` in the `plugin.shavit-hud.cfg`
