### ISSUE TITLE
Third person style

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#140]
An actual working third person style, that blocks "firstperson" being typed in console, actually the dumbest command in csgo \o/

**Comment by shavitush** [comment]
i'll do it exclusive to csgo because css thirdperson is buggy af

**Comment by Technoblazed** [comment]
Thanks :3

**Comment by Technoblazed** [comment]
I'm gonna give this a go implementing for csgo, seems super easy to do now. Main parts are just blocking the thirdperson and first person commands in console.

**Comment by strafe** [comment]
Any luck with this @Technoblazed? I haven't found a nice way to do it yet since firstperson is a client command and not cheat protected, smlib's thirdperson function also seems to not be appropriate as it's more like mayamode than normal thirdperson with deathcam or chase mode. Not sure if you can even check if a player is in the normal thirdperson mode if so I haven't found one yet so maybe Zipcore's way is the only way... just spam thirdperson with ClientCommand.

**Comment by Nickelony** [comment]
I think you can use the [AddCommandListener](https://sm.alliedmods.net/new-api/console/AddCommandListener) function to block it, but I'm not sure.

**Comment by shavitush** [comment]
@Nickelony doesn't work for client sided commands

**Comment by shavitush** [comment]
1.5 year bump but it's apparently not possible to block the firstperson/thirdperson commands.. unfortunate, closing

**Comment by Nickelony** [comment]
It's easily possible lol

**Comment by shavitush** [comment]
i really don't think it's a good idea to send client commands every tick

**Comment by Nairdaa** [comment]
It's a very bad idea, especially with convars like this. You could abuse it on other styles, like SW with a simple spam macro. It's not safe.

**Comment by Nickelony** [comment]
> i really don't think it's a good idea to send client commands every tick

CS:GO does that all the time just saying.
