### ISSUE TITLE
Rankings Issues

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#154]
- After getting a WR and doing !rank, the client remains unranked.
  - Does not receive a rank and has no chat tags, nor clantags.
  - I think something is inverted: https://gyazo.com/8e643c1531fd77cae4547869d7a9a777
- First record set on a map is receiving 49.99 points.
- 49.993 + 24.491 = 73.26? Nope D: Actually is 74.484, I know it's only 1, but would annoy someone else.

**Comment by shavitush** [comment]
> After getting a WR and doing !rank, the client remains unranked. 

weird, i'll take a look

> First record set on a map is receiving 49.99 points.

sourcemod's rounding ughhh, i'll fix it though

> 49.993 + 24.491 = 73.26? Nope D: Actually is 74.484, I know it's only 1, but would annoy someone else.

49.993 = 100% = 49.993
24.491 = 97% (dropped by 3% in weighting) = 23.75627

I thought you knew we use a weighting system :/

**Comment by shavitush** [comment]
anyways ok this new plugin is a really big mess, i'll rewrite it all this week and try to make it actually make sense

**Comment by Technoblazed** [comment]
Is anybody currently using the ranking system, if so, what are the outlying issues with itself and chat?

**Comment by shavitush** [comment]
i think you won't gain point and rank calculation will be broken

**Comment by Technoblazed** [comment]
But the link between shavit-chat <-> shavit-ranking is that they both rely on each other correct?

**Comment by shavitush** [comment]
shavit-chat relies on shavit-rankings, but not vice versa

**Comment by theSaint92** [comment]
While writing my simple alternative ranking system i found an issue, that might help u to fix ranking :)

The problem was that in shavit-core was useing REPLACE query that was setting points = 0 (default value) every time a player connected to server. You can check fix of shavit-core here https://github.com/theSaint92/bhoptimer/commit/f888372c63bdc2bb51aff31b9207d59588be2611#diff-91c83275495c1d98b0a734a4504d2994

PS. I wouldn't recommend to use my alternate ranking system yet, since queries i used are quite heavy and im getting 4/5 "Lost connection to MySQL server during query" errors daily. I will work on optimalization and improvement soon

**Comment by Nickelony** [comment]
Here's a working version of shavit-rankings made by zipcore: https://pastebin.com/raw/iuz6bgky

He tried to fix the plugin just so it works, but the rankings are killing the mysql database so it's unusable, but maybe this can help you in the future.

**Comment by shavitush** [comment]
I'll look into it soon and try optimizing the plugin, thanks.

**Comment by Nickelony** [comment]
oh and this in shavit-core:

```
char[] sQuery = new char[512];
	FormatEx(sQuery, 512, "REPLACE INTO %susers (auth, name, country, ip, lastlogin) VALUES ('%s', '%s', '%s', '%s', %d);", gS_MySQLPrefix, sAuthID3, sEscapedName, sCountry, sIP, GetTime());
```

replace with:
```
char[] sQuery = new char[2048];
	
	if (gB_MySQL)
		FormatEx(sQuery, 2048, "INSERT INTO %susers (auth, name, country, ip, lastlogin) VALUES ('%s', '%s', '%s', '%s', %d) ON DUPLICATE KEY UPDATE name = '%s' , country = '%s', ip = '%s', lastlogin = %d;", gS_MySQLPrefix, sAuthID3, sEscapedName, sCountry, sIP, GetTime(), sEscapedName, sCountry, sIP, GetTime());
	else FormatEx(sQuery, 2048, "REPLACE INTO %susers (auth, name, country, ip, lastlogin) VALUES ('%s', '%s', '%s', '%s', %d);", gS_MySQLPrefix, sAuthID3, sEscapedName, sCountry, sIP, GetTime());
```

and this
`FormatEx(sQuery, 512, "CREATE TABLE IF NOT EXISTS `%susers` (`auth` VARCHAR(32) NOT NULL, `name` VARCHAR(32), `country` VARCHAR(128), `ip` VARCHAR(64), `lastlogin` %s NOT NULL DEFAULT -1, `points` FLOAT NOT NULL DEFAULT 0, PRIMARY KEY (`auth`));", gS_MySQLPrefix, gB_MySQL? "INT":"INTEGER");`

with this:
`FormatEx(sQuery, 512, "CREATE TABLE IF NOT EXISTS `%susers` (`auth` VARCHAR(32) NOT NULL, `name` VARCHAR(32), `country` VARCHAR(128), `ip` VARCHAR(64), `lastlogin` %s NOT NULL DEFAULT -1, `points` FLOAT NOT NULL DEFAULT 0, PRIMARY KEY (`auth`)%s);", gS_MySQLPrefix, gB_MySQL? "INT":"INTEGER", gB_MySQL ? ", UNIQUE KEY `auth` (`auth`)" : "");`

It's because the points are reseting on join and mapchange.

**Comment by Nickelony** [comment]
I think this is the next big think you should start working on because everyone is waiting for a fully functional rankings plugin that delivers all the necessary features (and doesn't suck).

I don't think you have to rewrite your plugin since It's very good and I gave you a (almost) fully working version of it. The only think you have to do is to optimise it, because for some reason it's killing the database within 10 seconds. xD

**Comment by shavitush** [comment]
I'll rewrite it because I don't like the way I did things before, no worries! Rankings are basically the last thing I need to do before the timer is out of beta :).

**Comment by shavitush** [comment]
Closing as I made my own issue with a new design: #465
