### ISSUE TITLE
Rewrite most of the zones plugin

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#161]
The current one is a mess, @ofir753 had a big part in it and it's pretty much a clusterfuck for me because I don't understand any of the basic math being done there and it makes it hard for me to even add new stuff because of it :/

So.. I need to rewrite nearly all of it.

Important stuff:
* ~~Get rid of the `MapZones` type and straight up use `int` instead. The current method is messy and I cast from `MapZones` to `int` (and vice versa) too often.~~
* ~~Make a hard limit of 64 zones.~~
* ~~Cache zones properly with Dynamic or `any` types for the sake of simplicity.~~
* ~~Use `trigger_multiple` for zones instead of the current implementation.~~
* ~~Fully optimize zone drawing, it's a big mess as of now.~~
* ~~Needs to be compatible with the current database structure or either have it auto-migrate to a new format.~~
* ~~Allow every zone to be created more than once, except for start/end (for main and bonus).~~

Note: This will get rid of zone rotations. The math is too heavy to run per-tick and per-client which kills server performance. This plugin was meant to be simple.. but the zones plugin doesn't allow it to be simple :(.

**Comment by Technoblazed** [comment]
> Needs to be compatible with the current database structure or either have it auto-migrate to a new format.

= No rezoning? :3

**Comment by shavitush** [comment]
nope :)

**Comment by Technoblazed** [comment]
:^)

**Comment by shavitush** [comment]
@StrafeHack sure, would be super easy to do with triggers

**Comment by Kryptanyte** [comment]
Uhh, so I've mostly done this already if you want to take a look at it/use some of it, still got a few things to finish in it though like polygonal zones (I removed zone rotation because the math scared me and I wanted to make weird shapes with some zones). 

I use a completely different method of storing zones and database format from your current setup but from memory it should be easy to convert (automatically) to a new format as you said.

**Comment by shavitush** [comment]
Could you show me your database format? Do you use triggers?

**Comment by Kryptanyte** [comment]
Rather than splitting it up into multiple variables I'm making an enum and a single multi dimensional array to hold all the zone information:
![ss 2016-08-20 at 02 40 05](https://cloud.githubusercontent.com/assets/6505861/17813479/a6ab34f6-667f-11e6-8142-f931a7612708.png)

Basically you can make as many of each zone as you want using this layout along with changing it so the zones plugin handles the checking of players zone status (in zone or out of one) and starts a forward on a zone update with the client, zoneid they were in and it's type and the zoneid and type they are in now so it's easy to add new zones + functionality in whatever plugin you need it:

![ss 2016-08-20 at 02 51 56](https://cloud.githubusercontent.com/assets/6505861/17813830/118bd3c4-6681-11e6-868b-82b2171a6469.png)

I haven't tried using triggers yet because I'm not sure how they would handle the polygonal zones, since the only information I could find on them only seemed to making square triggers but it is something I want to play around with because it means that I wouldn't have to ray trace to see if a player is in the zone

My database layout:
![ss 2016-08-20 at 02 44 16](https://cloud.githubusercontent.com/assets/6505861/17813623/3524dcaa-6680-11e6-8c42-fcef9e3a4231.png)

Square zones are stored in the px, py, pz, varchar cells as px: "100.000,200.000".. etc and gets split in the database callback.

**Comment by Technoblazed** [comment]
That's pretty neat

**Comment by shavitush** [comment]
The enumeration couldn't be really used as I want to keep the consistency of the transitional syntax. That's a reason I wanted to start using Dynamic to cache zones. But I do like the idea of having a structure and this is what I plan on doing!

Hopefully I'll get around to doing most (if not all) you've done when I start working on zones again.

**Comment by Kryptanyte** [comment]
When you say Dynamic are you referring to the new dynamic arrays
`int Zones[] = new int[128]`
Kind of thing?

Because all the enum is there for is to structure the MapZones array (I'm actually missing a couple of things out of the enum like zone specific settings etc, I haven't figured out how I want to do them yet) and so that it's easy to read and write anything to do with zones.

I think I might be misunderstanding your reasons for Dynamic or I've missed something entirely I'm not sure. Either way I'm more than happy to lend a hand with this as I'm converting an old fork of your timer to a surf timer and might have a few different ways of doing things that might be good

**Comment by shavitush** [comment]
No, I mean [Dynamic](https://forums.alliedmods.net/showthread.php?t=270519)! Basically handles that I can store a 'struct' on them

**Comment by Kryptanyte** [comment]
Oh, I didn't even know that existed. My bad!

**Comment by shavitush** [comment]
Finished implementing *most* of the things I wanted to. But there's some issue I've been trying to fix for 2 hours already and I can't really figure it out.. the triggers' bounding box is a bit bigger than what it should be (it's about 16 to 20 units larger than what I see visually).

Does anyone know what I may have done wrong? I'm clueless, unfortunately. I've added some debugging so you can see it in action:

```sp
public void StartTouchPost(int entity, int other)
{
	if(!IsValidClient(other, true))
	{
		return;
	}

	Shavit_PrintToChat(other, "Entered: %s", gS_ZoneNames[gA_ZoneCache[gI_EntityZone[entity]][iZoneType]]);
}

public void EndTouchPost(int entity, int other)
{
	if(!IsValidClient(other, true))
	{
		return;
	}

	Shavit_PrintToChat(other, "Left: %s", gS_ZoneNames[gA_ZoneCache[gI_EntityZone[entity]][iZoneType]]);
}
```

**Comment by strafe** [comment]
@shavitush isn't that because using triggers counts you as inside the zone as long as any part of you is touching it and the old method only counts it if your models mid-point is inside the zone.

**Comment by shavitush** [comment]
That might be it! I'll research further.

**Comment by strafe** [comment]
@shavitush Mehis' timer also does this, the trigger zones in blacky's don't work so everyone is forced to use the old method with that timer. Maybe you could contact the trigger so it acts as expected?

**Comment by shavitush** [comment]
No worries, it's solved now :). I'll be sending a pull request in a moment.

**Comment by Kryptanyte** [comment]
You probably won't be super interested in this but I took your idea of using Dynamic for zones and wrapped it in a methodmap so it looks more 'object orientated'. eg:

```
#define Zone_Group                      "KT_Int_Zone_Group"

methodmap Zone < Dynamic
{
    public Zone(int ZoneID = -1)
    {
        Zone z;
        
        if(ZoneID != -1 && KT_GetZoneCount() >= ZoneID)
        {
            z = view_as<Zone>(KT_GetZoneOffset(ZoneID));
            
            if(z.IsValid)
                return z;
        }
        
        z = view_as<Zone>(Dynamic());
        gI_ZoneCount++;
        
        return z;
    }
    
    property int Group
    {
        public get()
        {
            return this.GetInt(Zone_Group);
        }
        public set(int value)
        {
            this.SetInt(Zone_Group, value);
        }
    }
}
```

Usage example:

```
Zone NewZone = Zone();
NewZone.Group = 1;

PrintToServer("%i", NewZone.Group);
```

There's a bit more to initializing a zone that what's here. You can request a already existing zone with `Zone(index)` where index is 0 or higher, it will automatically get the Dynamic index from an arraylist stored within the plugin.

**Comment by shavitush** [comment]
That's pretty neat! But I decided to not go with Dynamic for this purpose after all, as you can see in #372.

**Comment by Kryptanyte** [comment]
Yeah I noticed, I just thought I would share as it might be helpful for you at some point.
