### ISSUE TITLE
Add SHSW style

### ISSUE THREAD

**Issue by Massta** [shavitush/bhoptimer#239]
A friend suggested that adding the SHSW style would be a good improvement, and it shouldn't be _too_ hard to implement.
From my understanding it's the same as HSW, but the user is also allowed to use the combination of a+s and d+s, in addition to a+w/d+w.
Would be cool if somebody could take care of that :]

**Comment by Technoblazed** [comment]
Pointless style :|

**Comment by Massta** [comment]
Damn haters :[

**Comment by Technoblazed** [comment]
@Massta, Can you give me AN EXACT word for word explanation of what this style even is? If your answer is no, then it's even more pointless.

**Comment by Massta** [comment]
Yes I can. HSW is the combination of normal and W-only, SHSW would be the combination of normal and SW. A friend gave me a beautiful presentation why SHSW should be a thing; even if it allows "cheated" records (which could probably be negated by disallowing +forward and +back at the same time). I don't have more time to explain right now because I am at uni, but I'll get to that later.

**Comment by del6597** [comment]
I still don't see the point or even how this style is supposed to work.

**Comment by strafe** [comment]
It's not really a pointless style, every major/popular timer besides Zipcore's timer supports this style. The style is played less than sideways and legit but is probably on par with styles like A-Only and D-Only for playtime, it's much easier for most players than those two as well.

Since Massta didn't give a very clear description of what the style is I'll explain it briefly, the style is identical to Sideways or W-Only for everything except key-restriction, when playing surf half-sideways you can only move if you're holding W & A or S & D (some timers can do the opposite combinations too), in bTimes that looks something like this `(vel[0] > 0.0 && vel[1] < 0.0) || (vel[0] < 0.0 && vel[1] > 0.0)` this forces you to 
 strafe at a 45° angle but of course you can look around as well like on Sideways and W-Only.

These videos should showcase how the style is played well. [Short gmod run](https://www.youtube.com/watch?v=vUjRBlVJKr8), [Pretty bad strafe run](https://www.youtube.com/watch?v=acTjF6kEQIw), [fly map run](https://www.youtube.com/watch?v=1U12Iz7O6bE).

Clearly there's a bad reception to the idea of adding this style but considering how many other timer's support it (even OpenTimer) I think it should be added before release.

**Comment by shavitush** [comment]
Thanks for bringing up those points @strafe!

**Comment by shavitush** [comment]
Here's how the input detection looks like. Can you confirm that I've implemented it properly, @strafe?

![Surf HSW demonstration](https://user-images.githubusercontent.com/3672466/28237549-b4e823a2-694a-11e7-9acf-6d0ed1acedda.jpg)

**Comment by strafe** [comment]
@shavitush I'll test it tomorrow for sure.

**Comment by strafe** [comment]
@shavitush as long as you don't press a combination after exiting the start while in-air you are able to play completely unrestricted like Normal.

If everyone knew how the style was meant to be played I think the best option would be to just restrict all in-air movement until a combination has been chosen but this could confuse new players or just most players in general so many force WA/SD if they are out of the start zone in-air and aren't doing a valid input, up to you though.

**Comment by shavitush** [comment]
@strafe is this fine? Just tested gameplay (with those binds, because I can't SHSW for my life) on a 5:30 minutes long run (bhop_fps_max_sr) and everything seemed smooth, couldn't find issues on my own. But I never really played this style so I'm not one to decide.

```
alias "+aw" "+moveleft; +forward"
alias "-aw" "-moveleft; -forward"
alias "+ds" "+moveright; +back"
alias "-ds" "-moveright; -back"
bind "d" "+ds"
bind "a" "+aw"
```

**Comment by strafe** [comment]
Seems complete now.
