### ISSUE TITLE
Timelimits randomly changing on some maps for no reason.

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#289]
After the "Pull requests" update, the timelimits had changed from 15 minutes to 20 / 60 minutes, even if I didn't change anything in shavit-timelimit's config file. After disabling shavit-timelimit.smx the timelimits went normal again.

**Comment by Technoblazed** [comment]
shavit-timelimits uses an average of map times, are you sure this isnt what's causing it...

**Comment by Nickelony** [comment]
Yes, but I've never had to disable it till that moment. speedrun_ maps weren't affected by this plugin and idk if it should affect them now.

**Comment by shavitush** [comment]
well.. apparently i always forgot to call the calculation function in shavit-timelimits so it never took effect until just recently - i noticed it because i've never used the module myself, but i recently started my csgo server again and noticed it's broken, i had to fix it

you might want to disable it if you don't need the dynamic timelimits
