### ISSUE TITLE
Cleanup requirements

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#419]
The requirements and optional requirements sections in the README are pretty confusing, I even saw a video on YouTube of someone trying to install the timer and saying they didn't understand why things were listed twice. (it's been removed now idk why)

Personally I think if things have to be listed twice because you're referencing the include and the plugin/extension that should be made clear and things that are actually included in this repo like the dynamic, dhooks and rtler includes shouldn't be included in the (optional) requirements at all.

**Comment by shavitush** [comment]
Will redo the requirements part after #417, as it'll be more relevant then.

**Comment by strafe** [comment]
@shavitush just curious, why doesn't the plugin just force `sv_disable_immunity_alpha 1` if the server has a custom opacity value set?

**Comment by shavitush** [comment]
Good point, I'll force it.

**Comment by strafe** [comment]
@shavitush one more thing about the requirements, why was Bunnyhop Statistics corrected to have `CS:S Only` after it when there's no mention that I can see on the alliedmods thread or it's own github page about it being limited to that game?

**Comment by shavitush** [comment]
Bunnyhop Statistics isn't CS:S only.

There's just no reason to use it for the CS:GO HUD because for CS:S it shows the player's scrolls on center text, which overrides the regular HUD in CS:GO. Also you can't really get scroll styles to work well in CS:GO so it's pointless.

If I can somehow fit it to the CS:GO HUD then great! I'm not sure if the HUD objects are any good for this kind of things in CS:GO, but if they are, it can be probably put outside the current HUD.

Here's a video of how it looks in CS:S - https://streamable.com/d74g4
The number on the left is the amount of scroll inputs since I left the ground and the right number is the amount of scroll inputs from the last jump.
