### ISSUE TITLE
WR & PB Inconsistency in HUD

### ISSUE THREAD

**Issue by exploiteddna** [shavitush/bhoptimer#492]
https://i.gyazo.com/74234cd9ff51626287e92bd6fc5e14d6.png

These are the same run, but the time shows up slightly different when comparing them. I think this is another issue sourcemod rounding.. maybe.

This is not a huge problem, but one of my admins found it so I figured I'd let you know

**Comment by Technoblazed** [comment]
Probably just rounding, but that link is embedded horribly :P

**Comment by michaelrw10** [comment]
sorry @Technoblazed im not the greatest with this formatting.. i looked for an image embed on the toolbar but didnt see one :/
dont know markdown very well

but yeah, probably rounding, but you you know bhoppers are a bunch of snobs and want everything perfect or else its nonstop "hey, server owner dude, why dont you fix your timer bruh its broken.. look at that time.. rip timer" 
xdxd

**Comment by shavitush** [comment]
I'm not sure if I can do anything about this unfortunately :/

**Comment by strafe** [comment]
It should be rounding the same for both of them though either way. From what I've seen while printing calculated floats in SM they usually have a +/- of 1 at the least significant digit, so 0.500 may be shown as 0.501 or more commonly as 0.499, a difference of 2 doesn't seem right.

**Comment by shavitush** [comment]
@strafe but the database engine is the one that returns one of them, therefore it might be an issue of rounding with both

**Comment by strafe** [comment]
I think he should see if it persists through a restart and if so provide a copy of the database to be sure, but it may be nothing.

**Comment by rtldg** [comment]
There was no way to get mysql to return the exact bit-pattern of a float for certain values so I added the column `exact_time_int` to the table `playertimes` which is just the 4-byte float interpreted as a 4-byte int. https://github.com/shavitush/bhoptimer/commit/a6be0127ee9d44c82cfe146e0da22d255398f825
So yeah, any new times set using that commit or later shouldn't be affected by these rounding issues

**Comment by strafe** [comment]
@rtldg does this solve the issue? I've seen various approaches to this such as storing the amount of ticks along with the tickrate in the database, etc. but it seems no matter what you do, when you need to display it as a float, casting it in SM will always introduce some rounding inaccuracy.

**Comment by rtldg** [comment]
>does this solve the issue?

It removes any rounding inaccuracies for any new times which is as solved as this can be in my opinion. For current WRs it would be possible to grab the time float from the replay file and then also shoving that into `exact_time_int` for older runs, but I haven't decided on if I'll actually do that yet.

>I've seen various approaches to this such as storing the amount of ticks along with the tickrate in the database, etc.

I do think ticks + tickrate would be a good thing to do but implementing that would be more work than just adding another column right now due to the tick interval offset stuff and timescaling midrun stuff. I would like to do that eventually though.

>but it seems no matter what you do, when you need to display it as a float, casting it in SM will always introduce some rounding inaccuracy.

The time float won't change due to rounding inaccuracy when going from sourcemod->mysql->sourcemod anymore (with new times) since it's just reinterpreting the bytes with `view_as<int>(time)` & `view_as<float>(exact_time_int)`.

Displaying/formatting floats can differ though, yeah, but those floats aren't used for the WR/PB cache in memory anymore, so that shouldn't be too bad
