### ISSUE TITLE
Overwriting replaybot if its WR has been removed.

### ISSUE THREAD

**Issue by m-yk** [shavitush/bhoptimer#602]
You have a cheated WR & replay bot, you remove all the cheaters times from the database but the bot still remains, nothing awful about that, but when the current WR (would've been #2 had the cheated time not been removed) gets beaten by a legitimate player, the cheated bot still remains instead of there being a new bot from the legitimate player who now has WR.

**Comment by shavitush** [comment]
This isn't possible at the moment due to floating number precision (which will be awful on very short maps).
The only solution I can think of at the moment is to implement #568 for such cases, and have it delete the replay data owned by the wiped player.
This issue happens because you manually removed data from the database, without going through their rank 1s and deleting their replays.

An alternative that I suppose (for the new replay format only) is to compare the stored SteamID of the replay bot's owner and only consider it valid for gameplay if they do have a time on the map/style/track. What do you think?

**Comment by shavitush** [comment]
Solved within #568
