### ISSUE TITLE
[Request] Cvar for disable hide commands

### ISSUE THREAD

**Issue by Master-GitHub** [shavitush/bhoptimer#650]

**Comment by strafe** [comment]
@Master-GitHub what's the use case for this?

**Comment by Master-GitHub** [comment]
@strafe Some people don't want to hide all commands on chat.

**Comment by strafe** [comment]
Ah you mean hiding commands in the chat not the `!hide` command. Personally I don't think that should be in the timer at all since SourceMod already has the ability to do this. The only reason I can think of is that most people never touch `core.cfg` and don't know the options exist.

https://github.com/alliedmodders/sourcemod/blob/master/configs/core.cfg#L32-L40

**Comment by Master-GitHub** [comment]
Bump
