### ISSUE TITLE
[Request/Issue] forced sv_enablebunnyhopping

### ISSUE THREAD

**Issue by 2x9Mon** [shavitush/bhoptimer#721]
Let the maps' point_servercommand change sv_enablebunnyhopping value.
It kinda ruins all the point of "_strafe" maps

**Comment by Nairdaa** [comment]
```
	{
        "name"                "Scroll - _strafe"
        "shortname"            "STRF"
        "htmlcolor"            "279BC2"
        "command"            "strafe;strafe;STRF"
        "clantag"            "STRF"

        "autobhop"            "0"
        "easybhop"            "0"
		
		"bunnyhopping"		"0" // Per-style sv_enablebunnyhopping. Leave as 1 if you want bunnyhopping to maintain player speed. This setting will override _strafe map settings.

        "airaccelerate"        "100.0"
        "runspeed"            "250.00"

        "block_pleft"        "1"
        "block_pright"        "1"
        "block_pstrafe"        "1"
    }
```

**Comment by 2x9Mon** [comment]
Yeah, but that's not what I'm talking about. Making a separate style for _strafe maps isn't an option at all. 
All the _strafe maps are SUPPOSED to be played on sv_enablebunnyhopping 0, regardless of chosen style. There's a purpose of "point_servercommand" on all of these maps

**Comment by Nairdaa** [comment]
I do understand your point, altho bhop_sahara is an autobhop map (isn't?) yet the point_servercommand enforces 100aa, wich is uhm... Well, you say it ;)

Anyway, things are getting changed, show goes on, and you gotta deal with the fact that most of the people tend to like playing auto instead of scroll. I'm a scroller myself, so I am indeed on your side, but enforcing such setting is not a good idea for a timer. If they want to actually play _strafe the way it's meant to be played - let them just type that !strafe command on these maps imo.

If you're really interested in having that enforced, I can edit shavit's plugin so it doesn't automatically strip the point_servercommand out of the maps (if it even does?) for you.

// Well, no, the timer itself doesn't enforce it being removed.

**Comment by shavitush** [comment]
_strafe maps are the reason the settings get forced to begin with! this is intentional and it was my design choice to allow players to play any map at whatever settings they desire
