### ISSUE TITLE
random spawn bug after map change

### ISSUE THREAD

**Issue by Saengerkrieg12** [shavitush/bhoptimer#752]
sometimes if the map was changed and you go into a team you will not spawned.

**Comment by shavitush** [comment]
because zones were not loaded yet due to the database being overloaded. this should be fine after 2.5 because i optimized the database by a lot! make sure to update your database to follow the format like the wiki page suggests: https://github.com/shavitush/bhoptimer/wiki/4.3.-Extra:-Database-maintenance
