### ISSUE TITLE
Timer crash when combined with trikz redux plugin.

### ISSUE THREAD

**Issue by Zetsuyaa** [shavitush/bhoptimer#836]
As title says, the timer crashes when two players finish a map. Does anyone know a possible fix? Thanks. Only happens when both have timer. If only 1 of the partnership has the timer the server won't crash.

**Comment by blankbhop** [comment]
trikz is not updated to work with the recent version

**Comment by Zetsuyaa** [comment]
What version should i use for it to be compatible?

**Comment by kidfearless** [comment]
The issue is with the redux plugin for the most part. Once one player finishes it tries to tell the timer to finish the other players time. which causes a loop of finish timer calls and on finish forwards. To fix this you would need to recompile the trikz plugin to check if their timer is running before trying to call the finish timer native.
