### ISSUE TITLE
shavit-rankings 

### ISSUE THREAD

**Issue by Rinski16** [shavitush/bhoptimer#854]
When I pass map shavit-rankings doesn't give me points. I need to type !recalcall and it will give me points. How can I fix this ?

**Comment by Nairdaa** [comment]
You can't. It's  fucked up since ages. I got a hude db and the poiints just won't update.

**Comment by Rinski16** [comment]
> 
> 
> You can't. It's fucked up since ages. I got a hude db and the poiints just won't update.
> 
> Also "recalcall" will just timeout for me.

Anyway to fix or better to switch to other timer ?

**Comment by shavitush** [comment]
Points are updated for the users only after reconnecting/map changes, to not stress the database.

**Comment by Nairdaa** [comment]
They never update for me anymore. The database is just too big I guess. It times out.

**Comment by Nairdaa** [comment]
The records get saved etc tho. Just the points don't update.

**Comment by rtldg** [comment]
> When I pass map shavit-rankings doesn't give me points. I need to type !recalcall and it will give me points. How can I fix this ?

What shavit said "Points are updated for the users only after reconnecting/map changes, to not stress the database."



> You can't. It's fucked up since ages. I got a hude db and the poiints just won't update.

Probably due to `shavit_rankings_weighting` https://github.com/shavitush/bhoptimer/issues/979 or the map recalc being slow

> Also "recalcall" will just timeout for me.

Should be fine in https://github.com/shavitush/bhoptimer/commit/dc9f39bdf31413a0084b0184e1488a6de1ae9fe4 / very_good_yes / next release
