### ISSUE TITLE
Tying your own record counts as beating a record

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#878]
This is an issue on segmented styles where someone can put a checkpoint right before the end and spam teleport and keep beating the map and spamming chat/wr sound even though they are just tying their record.

Instead tying your own record should act the same as getting a slower time.

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-wr.sp#L1980

It should never happen :/

**Comment by rtldg** [comment]
This happens when sending the time float to SQL and back which causes it to differ.
`Shavit_OnFinish` -> `SQL_OnFinish_Callback` -> `UpdateClientCache` -> [`SQL_UpdateCache_Callback`](https://github.com/shavitush/bhoptimer/blob/b7114c2854c5c7bb22a5aaef8096faaae3a443d4/addons/sourcemod/scripting/shavit-wr.sp#L479) where the player's record is being set to the float returned from SQL.

This should be fixable with this https://github.com/rtldg/bhoptimer/commit/b45905d74c15a63f00a7c7b20fbe2d7ae29ffa91
or by removing the call to `UpdateClientCache` here https://github.com/shavitush/bhoptimer/blob/b7114c2854c5c7bb22a5aaef8096faaae3a443d4/addons/sourcemod/scripting/shavit-wr.sp#L2179
Not sure if `UpdateClientCache` is needed there

**Comment by Nairdaa** [comment]
> float pepega

:D

**Comment by rtldg** [comment]
Went ahead and added an `exact_time_int` to the SQL table `playertimes` so the actual bit representation of the `time` float is saved. This was done because mysql modifies the float slightly even if prepared-queries are used and the float isn't just formatted to a string. It's jank, but it's the best our current technology can achieve. https://github.com/shavitush/bhoptimer/commit/a6be0127ee9d44c82cfe146e0da22d255398f825
