### ISSUE TITLE
Built-in mapzones are invisible

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#891]
pls fix k thanks i owe you a pizza slice

**Comment by kidfearless** [comment]
There isn't really a good way to do this without doing something crazy like in GammaCases Show Player Clips plugin. The only data I'd really have to go off of is the brushes mins and max, which I think would  only work if the brush is alligned to grid. Since brushes can be any shape they aren't guaranteed to be alligned to grid this feature probably won't be added.
