### ISSUE TITLE
Account for tick perfect jumps for zone offset calculations.

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#941]

**Comment by rtldg** [comment]
I'm not really sure what `Account for tick perfect jumps for zone offset calculations.` means.
Jumping from inside the start zone lets you have a 0.0 offset every time (as long as the server settings allow you to jump in the start zone).
So for that reason & also that a lot of servers have been setting `shavit_zones_box_offset` to 0 instead of 16, I think this issue is fine to close unless there's something else to do.

I might change the default of `shavit_zones_box_offset` to `0` eventually too.
