### ISSUE TITLE
[ Bug ] Points calculation

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#979]
[S t r a f e] Kreedzor • it sucks, apparently it can't count for more than 100 maps
*[Talented] an idiot sandwich | you what
*[Talented] an idiot sandwich | i have almost 2k maps on ultima
*[#8] Ģяillø, The GrannyWanker | Yeah, that's at least what maem said xD
*[#8] Ģяillø, The GrannyWanker | The best 100 maps you played
[S t r a f e] Kreedzor • well, it doesn't add anymore points to ppl who completed too many maps, according to maem
[S t r a f e] Kreedzor • so if you get a wr on a t2 map
[S t r a f e] Kreedzor • it won't add points
*[#8] Ģяillø, The GrannyWanker | According to tier and..time spent, yeah?
*[#8] Ģяillø, The GrannyWanker | SO basically if you complete a t8 in 16 hours, you get shit loads of pts xD
[S t r a f e] Kreedzor • i never got interested in this shit tho
*[Talented] an idiot sandwich | gonna create a bug thread on git
*[#8] Ģяillø, The GrannyWanker | But it counts even if other people played it

**Comment by rtldg** [comment]
This is seems to be due to `shavit_rankings_weighting` being less than `1.0`.
For example, if I have the following points from playertimes and my `shavit_rankings_weighting` is `0.8`
`225.659  195.279  144.417  37.6218  0.150305`
it'll do `(225.659 * 1) + (195.279 * (.8^1)) + (144.417 * (.8^2)) + (37.6218 * (.8^3)) + (0.150304 * (.8^4))`
which gives `493.633006118` instead of `1.0` giving `603.127104`. and eventually the multiplier will give you nothing.

that seems to be how it was intended to work with `shavit_rankings_weighting` having a default of `0.975`
just set `shavit_rankings_weighting` to `1.0` if you don't want that
